export const pink = "#DE4370"
export const black = "#4A4A4A"
export const gray = "#D6D6D6"
export const white = "#FFFFFF"
export const facebook = "#4267B2"
export const darkPink = "#F29D9D"
export const thinPink = "#FF388C"